kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Go
    image: golang:1.20
    commands:
      - cp .env.example .env
      - touch /drone/src/server/static/app.js
      - bin/test.sh
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov
    environment:
      CODECOV_TOKEN: 29a128f7-f56b-4d73-8ec8-da3803ec2c3c

  - name: Test Node
    image: satantime/puppeteer-node:18-bullseye-slim
    commands:
      - cp .env.example .env
      - npm ci
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - cp .env.example .env
      - shellcheck -x --exclude=SC1091 bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=DL4006 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: yandex/gixy:0.1.20
    commands:
      - gixy config/nginx/*

  - name: Test Makefile
    image: cytopia/checkmake:latest
    commands:
      - checkmake Makefile

  - name: Build Docker Container
    depends_on:
      - Test Go
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Makefile
      - Test Nginx
    image: plugins/docker
    settings:
      repo: reaction-pics
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh:1.6.4
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/reaction-pics/bin/deploy.sh master"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master
