kind: pipeline
type: docker
name: test

steps:
  - name: Test Go
    image: golang:1.25
    commands:
      - apt-get update && apt-get install -y xz-utils
      - cp .env.example .env
      - touch /drone/src/server/static/gen/main.js
      - touch /drone/src/server/static/gen/main.css
      - curl https://qlty.sh | sh
      - bin/test.sh
      - ~/.qlty/bin/qlty coverage publish c.out --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_0SkZ4hmucn2hlQSg

  - name: Test Node
    image: satantime/puppeteer-node:24-bookworm-slim
    commands:
      - cp .env.example .env
      - npm ci
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - cp .env.example .env
      - shellcheck -x --exclude=SC1091 bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=DL4006 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: getpagespeed/gixy:v0.2.7
    commands:
      - gixy config/nginx/*

  - name: Test Makefile
    image: cytopia/checkmake:latest
    commands:
      - checkmake Makefile

  - name: Build Docker Container
    depends_on:
      - Test Go
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Makefile
      - Test Nginx
    image: plugins/docker
    settings:
      repo: reaction-pics
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    environment:
      SSH_KEY:
        from_secret: ssh_key
    image: albertyw/ssh-client:4.1.8
    commands:
      - ssh-keyscan direct.albertyw.com >> /root/.ssh/known_hosts
      - echo "$${SSH_KEY}" > /root/.ssh/id_ed25519
      - chmod 600 /root/.ssh/id_ed25519
      - ssh albertyw@direct.albertyw.com reaction-pics/bin/deploy.sh master
    when:
      branch:
        - master
