kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Go
    image: golang:1.16
    commands:
      - ln -fs .env.example .env
      - touch /drone/src/server/static/app.js
      - bin/test.sh
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN: 29a128f7-f56b-4d73-8ec8-da3803ec2c3c

  - name: Test Node
    image: node:16
    commands:
      - apt-get update && apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libcups2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxss1 libxtst6 lsb-release xdg-utils
      - ln -fs .env.example .env
      - npm ci
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.example .env
      - shellcheck -x --exclude=SC1091 bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=DL4006 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: yandex/gixy:0.1.20
    commands:
      - gixy config/nginx/*

  - name: Build Docker Container
    depends_on:
      - Test Go
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Nginx
    image: plugins/docker
    settings:
      repo: reaction-pics
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/reaction-pics/bin/deploy.sh master"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master
